Fix potential endless loop in AggregatedBrailleTranslatorResult
mtmse/dotify.library pull request #14
Opened 2021-06-09 11:21 UTC by bertfrees

@kalaspuffar @PaulRambags There was a nasty bug in AggregatedBrailleTranslatorResult that for some reason hasn't been noticed yet until now.

2021-06-09 12:02 UTC, kalaspuffar approved these changes

2021-06-11 10:24 UTC, PaulRambags approved these changes

2021-06-11 13:45 UTC, kalaspuffar commented
PR approved, running regression tests.

2021-06-11 13:48 UTC, kalaspuffar commented
Check style issue:

> Task :checkstyleMain
[ant:checkstyle] [ERROR] /home/danielp/github/dotify.library/src/org/daisy/dotify/formatter/impl/row/AggregatedBrailleTranslatorResult.java:123: 'if' construct must use '{}'s. [NeedBraces]

2021-06-11 13:49 UTC, kalaspuffar requested changes

2021-06-11 13:49 UTC, kalaspuffar commented on src/org/daisy/dotify/formatter/impl/row/AggregatedBrailleTranslatorResult.java
> +            if (s.isEmpty()) break;
Add {}

2021-06-11 13:55 UTC, bertfrees commented
Yeah, I can't run these checks anymore because the test suite fails. I thought I could just ignore the two failing tests, but I didn't think of the checks. Can we do something about it?

- I need a command to just run the checks, not the tests suite
- or the test suite should pass (it should not depend on Hyphen)
- or we should set up a Github action to run the checks and make the report available for download

2021-06-11 17:31 UTC, kalaspuffar commented
Hi @bertfrees 

I could change the test only to run if you have the dictionary file, or perhaps we could add it to the repository. It's not large and under LGPL license. I don't know really what we need to disclose to add it.

https://extensions.libreoffice.org/en/extensions/show/swedish-spelling-dictionary-den-stora-svenska-ordlistan

Best regards
Daniel

2021-06-11 17:39 UTC, bertfrees commented
The problem I think is that you need the Hyphen library installed, not just the dictionary file. Checking for the dictionary file sounds like a practical solution.

2021-06-14 10:33 UTC, kalaspuffar approved these changes

2021-06-14 10:36 UTC, kalaspuffar commented
PR approved, running regression tests.

2021-06-14 12:33 UTC, kalaspuffar commented
Regression tests passed, merging.

2021-06-14 12:33 UTC, merged